In [1]:
import torch

In [2]:
def activation(x):
    return 1/(1 + torch.exp(-x))

torch.manual_seed(7)
features = torch.randn((1, 5))
weights = torch.randn_like(features)
bias = torch.randn((1, 1))
y = activation(torch.sum(features * weights) + bias)
y

tensor([[0.1595]])

In [3]:
# output y using matrix multiplication

y = activation(torch.mm(features, weights.view(5, 1)) + bias)
y

tensor([[0.1595]])

In [4]:
torch.manual_seed(7)
features = torch.randn((1, 3))

#Define the size of each layer in our network

n_input = features.shape[1]  # Number of input units, must match number of input features
n_hidden = 2  # number of hidden units
n_output = 1 # number of output unit

# Weights for input to hidden layer
W1 = torch.randn(n_input, n_hidden)

# Weights for hidden layer to output layer

W2 = torch.randn(n_hidden, n_output)

# bias term for hidden and output layer

B1 = torch.randn(1, n_hidden)
B2 = torch.randn(1, n_output)

h = activation(torch.mm(features, W1) + B1)
output = activation(torch.mm(h, W2) + B2)
print(output)

tensor([[0.3171]])


In [38]:
import numpy as np

a = np.array([1, 2, 3])
# print(type(a))
print(a.shape)
print(np.eye(2))

(3,)
[[1. 0.]
 [0. 1.]]


In [57]:
b =np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)

(2, 3)


In [40]:
import numpy as np

# c = np.zeros((2,3))
# c = np.ones((2,2))
# c = np.full((2, 3), 7)
c = np.eye(2, 3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]]


In [58]:
import numpy as np

b = np.random.rand(4,3)

print(b)

[[0.87311307 0.37774516 0.05770719]
 [0.19213388 0.03953089 0.71215362]
 [0.05845733 0.1625084  0.15160791]
 [0.46569605 0.21152739 0.04997349]]


In [59]:
c = torch.from_numpy(b)
c

tensor([[0.8731, 0.3777, 0.0577],
        [0.1921, 0.0395, 0.7122],
        [0.0585, 0.1625, 0.1516],
        [0.4657, 0.2115, 0.0500]], dtype=torch.float64)

In [60]:
c.numpy()

array([[0.87311307, 0.37774516, 0.05770719],
       [0.19213388, 0.03953089, 0.71215362],
       [0.05845733, 0.1625084 , 0.15160791],
       [0.46569605, 0.21152739, 0.04997349]])

In [61]:
c.mul_(2)
c


tensor([[1.7462, 0.7555, 0.1154],
        [0.3843, 0.0791, 1.4243],
        [0.1169, 0.3250, 0.3032],
        [0.9314, 0.4231, 0.0999]], dtype=torch.float64)

In [62]:
b   # Numpy array matches new value from tensor

array([[1.74622613, 0.75549033, 0.11541438],
       [0.38426777, 0.07906178, 1.42430725],
       [0.11691466, 0.32501681, 0.30321581],
       [0.9313921 , 0.42305478, 0.09994697]])